chore: update org name
Schrodinger-Hat/ImageGoNord-cli pull request #28
Opened 2024-10-15 16:27 UTC by Readpato

As title says, update org name wherever possible

2024-10-15 16:29 UTC, Wabri requested changes

2024-10-15 16:29 UTC, Wabri commented on src/image_go_nord_client/__init__.py
> +Email bug reports, questions, discussions to <social@schroedinger-hat.org>
```suggestion
Email bug reports, questions, discussions to <dev@schroedinger-hat.org>
```

2024-10-15 16:31 UTC, Readpato commented on src/image_go_nord_client/__init__.py
> +Email bug reports, questions, discussions to <social@schroedinger-hat.org>
Good idea 👍

2024-10-16 07:13 UTC, Wabri approved these changes

2024-10-16 07:15 UTC, Wabri commented
Looking forward to @BugliL's second look.

2024-10-17 13:00 UTC, BugliL approved these changes

2024-10-18 10:16 UTC, merged